// Initial State
function getInitialState() {
    return {
        // View State
        currentView: 'home',
        locationTab: 'notes',
        user: null,
        token: null,
        loading: false,
        error: '',
        success: '',
        darkMode: false,
        
        // Forms
        loginForm: { username: '', password: '' },
        registerForm: { username: '', email: '', password: '' },
        locationForm: { 
            name: '', 
            description: '',
            city: '', 
            country: '', 
            address: '', 
            latitude: null, 
            longitude: null, 
            rating: null, 
            category: '', 
            collection: '', 
            tags: '', 
            is_public: false,
            link: ''
        },
        collectionForm: { name: '', description: '', start_date: '', end_date: '', link: '', is_public: false },
        categoryForm: { name: '', icon: '', is_public: false },
        noteForm: { name: '', content: '' },
        activityForm: { type: '', date: '' },
        checklistForm: { name: '' },
        checklistItemForm: { name: '' },
        transportationForm: { 
            type: '', 
            from_location: '', 
            to_location: '',
            depart_time: '',
            arrive_time: '',
            depart_timezone: '',
            arrive_timezone: '',
            depart_latitude: null,
            depart_longitude: null,
            arrive_latitude: null,
            arrive_longitude: null,
            link: '',
            rating: null,
            is_public: false
        },
        lodgingForm: { name: '' },
        trailForm: { name: '', difficulty: '', length: null },
        visitForm: { start_date: '', end_date: '', timezone: '', notes: '' },
        
        // Data
        locations: [],
        collections: [],
        categories: [],
        allVisits: [],
        stats: null,
        countries: [],
        visitedRegions: [],
        visitedCities: [],
        countryRegions: [],
        countryVisitedRegions: [],
        regionCities: [],
        regionVisitedCities: [],
        selectedCountry: null,
        selectedRegion: null,
        selectedLocation: null,
        editingLocationId: null,
        locationNotes: [],
        locationVisits: [],
        locationActivities: [],
        locationChecklists: [],
        locationTransportation: [],
        locationLodging: [],
        locationTrails: [],
        
        // Search & Filter State
        searchQuery: '',
        filterCategory: '',
        filterCollection: '',
        filterRating: '',
        sortBy: 'name',
        collectionsSearchQuery: '',
        categoriesSearchQuery: '',
        worldTravelSearchQuery: '',
        regionSearchQuery: '',
        citySearchQuery: '',
        worldTravelFilterOption: 'all',
        worldSubregionFilter: '',
        regionFilterOption: 'all',
        
        // Pagination State
        currentPage: 1,
        itemsPerPage: 20,
        
        // UI State
        showAddLocation: false,
        showAddCollection: false,
        showAddCategory: false,
        showAddNote: false,
        showAddVisit: false,
        showAddActivity: false,
        showAddChecklist: false,
        showAddChecklistItem: {},
        showAddTransportation: false,
        showAddLodging: false,
        showAddTrail: false,
        locationsViewMode: 'list',
        worldTravelMode: 'countries',
        map: null,
        markers: [],
        gettingLocation: false,
        showTagSuggestions: false,
        addressSuggestions: [],
        showAddressSuggestions: false,
        searchingAddress: false,
        
        // Form Validation State
        validationErrors: {},
        
        // Additional Features State
        searchResults: null,
        searchResultsCount: 0,
        calendarEvents: [],
        calendarDays: [],
        calendarCurrentDate: new Date(),
        calendarView: 'month',
        calendarSearchFilter: '',
        selectedCalendarEvent: null,
        currentMonthYear: new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }),
        settingsSection: 'profile',
        useImperialSystem: false,
        selectedTheme: 'auto',
        profileUser: null,
        profileStats: null,
        profileLocations: [],
        profileCollections: []
    };
}
